name: Multiple-Job Workflow
on:
  workflow_dispatch:
jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      GREETING: "Hello"
      NAME: "Multi_Job Workflow"
    steps:
      - name: Show Envirpnment Variables
        run: |
          echo "Greeting: $GREETING"
          echo "Name: $NAME" 

  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: Run after First Job
        run: echo "This job runs after the first job."