name: Simple Environment Workflow

on:
  push:
    branches:
      - main       # for production
      - staging    # for testing
      - develop    # for development

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Display Environment Message
        env:
          # Use conditional logic to pick the correct secret based on the branch
          ENV_MESSAGE: ${{ github.ref_name == 'main' && secrets.ENV_MESSAGE_PRODUCTION || github.ref_name == 'staging' && secrets.ENV_MESSAGE_TESTING || secrets.ENV_MESSAGE_DEVELOPMENT }}
        run: |
          echo "Running in the environment based on branch ${GITHUB_REF_NAME}"
          echo "${ENV_MESSAGE}"

